
name: Master

on: [push]


jobs: 
 build:
   runs-on: ubuntu-latest
   steps:
      - name: Download CLI
        run: 
          echo "This is DIR::" $(pwd)
          echo "T" $PATH
           mkdir  assests/sfdx-Test
          

