#.github/workflows/main.yml
name: Scratch org for review
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
      
    - name: Authenticate DevHub
      run: |
        echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.HUB_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.HUB_SFDC_USER}}  -r https://login.salesforce.com
      env:
        SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}

    - name: Run Apex test
       mkdir  assests\Testunit
      run: node_modules/sfdx-cli/bin/run force:apex:test:run  -u atul.baviskar@enzigma.in   -d assests/Testunit 

    - name: Convert metadata into file of metadata formate
      run: node_modules/sfdx-cli/bin/run force:source:convert -r force-app/main/default -d ant/unpackaged
             