
name: Master

on: [push]


jobs: 
 build:
   runs-on: ubuntu-latest
   steps:
      - name: Download CLI
        run: 
           mkdir -p  /sfdx-project/assests/sfdx-Test
          

